id: I34874C47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:17:05+00:00'
last_modified: '2022-06-08T12:54:39.074077+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20112
  title: གནའ་རྒྱའི་ཚེ་ལོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '9988':
      image_group_id: I4990
      title: ''
      total_pages: 190
      order: 1
      base_file: 9988.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
