id: P010345
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:45:08.640330
source_metadata:
  id: bdr:W20112
  title: གནའ་རྒྱའི་ཚེ་ལོ
  author: ''
  volumes:
    455fce0423094cd8902f54252ae4f294:
      image_group_id: I4990
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
